stages:
  - build

build:
  stage: build
  image: node:18-alpine

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .npm/

  before_script:
    - npm ci --cache .npm --prefer-offline

  script:
    - echo "Executando build de produção..."
    - npm run build

  artifacts:
    paths:
      - dist/
    expire_in: 1 week

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
